const announcementData = [
  {
    time: '2020-11-13',
    title: '关于严防电信诈骗的提醒',
    href: '/a/news/shgg/207.html',
    imgPwd: '../ECMS_DGSJ/images/news/announcement-1-1.jpg',
    // imgPwd:
    //   'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtZ1Hq3pz7-J9sQytpCMgjjliJjRFaWV5EYw&usqp=CAU',
    img_src: '',
    desc: '近期，有不法分子以使馆工作人员名义致电华人华侨进行电话诈骗，或者将电话伪装成我馆证件咨询电话01-2196651四处拨打，扰乱我馆正常服务。在此，我馆郑重提醒：\n    一、我馆从即日起暂停使用证件咨询电话01-2196651进行对外联络，该电话仅用于接听，所有显示该号码的来电请不要接听或回拨。',
    id: 'announcement-1',
  },
  // {
  //   time: '2020-11-13',
  //   title: '关于公布近期签证受理条件的通知',
  //   href: '/a/news/shgg/206.html',
  //   imgPwd:
  //     'https://mmbiz.qpic.cn/mmbiz_png/SDrdLcd7UcMNuvIN7wAlmnBKmMrrEuMO4x4V7gJe3g0jc0Fd47ibFibG51eCFNmSjsuicY0W6bzvS83mVUTO0QIxw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
  //   img_src:
  //     'https://mmbiz.qpic.cn/mmbiz_png/SDrdLcd7UcMNuvIN7wAlmnBKmMrrEuMO4x4V7gJe3g0jc0Fd47ibFibG51eCFNmSjsuicY0W6bzvS83mVUTO0QIxw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
  //   desc: '一、为逐步有序恢复中外人员往来，中国驻爱尔兰使馆目前受理如下情形普通签证申请：\n    1、持2020年3月28日0时之后过期的工作、私人事务及团聚类居留许可（样式附后），如赴华事由与现持居留许可相符，能一并提交相应种类签证材料（详见我馆网站http://ie.chineseembassy.org/chn/qzfw/t1476168.htm《申请签证指南》）的外国公民（自2020年9月28日0时起，持有效中国工作类、私人事务类和团聚类居留许可的外国公民入境中国，无需重新申办签证）；',
  //   id: 'announcement-2',
  // },
  // {
  //   time: '2020-01-10',
  //   title: '关于赴科克市开展领事工作现场办公服务的通知',
  //   href: '/a/news/shgg/111.html',
  //   imgPwd: '',
  //   img_src: '',
  //   desc: '关于赴科克市开展领事工作现场办公服务的通知\n    中国驻爱尔兰大使馆领事部将于2019年12月13日（星期五）上午09:30至12:00在科克市（详细地址：The Kinsley Hotel, Victoria Cross,Cork）开展领事工作现场办公服务，受理华侨华人护照、旅行证、领事认证、公证及领取养老金资格审核表等证件业务（申办上述证件所需材料与在使馆领事部办理相同，办理护照、旅行证需在线填表预约）。由于签证申请需在使馆采集指纹，现场办公期间无法接受签证申请。特此通知。',
  //   id: 'announcement-3',
  // },
  // {
  //   time: '2019-12-10',
  //   title: '商会关于2018年度工作报告',
  //   href: '/a/news/shgg/41.html',
  //   imgPwd: '',
  //   img_src: '',
  //   desc: '1.\n    商会成立\n    2018年2月份开始筹建商会，3月7号召开第一次理事会议，表决审议通过了《爱尔兰科克华人商会章程》，9月23号在Cork\xa0City\xa0Hall\xa0在中国驻爱尔兰大使馆黄河参赞，潘好泉主任和\xa0科克副市长\xa0Fergal\xa0Dennehy,\xa0及现场500名嘉宾观众的见证下成功举办了商会成立庆典暨首届理事会就职典礼，并携手上海鼓舞东方艺术团为在场人员献上了一场精彩纷呈的视听盛宴。',
  //   id: 'announcement-4',
  // },
];

const shdtData = [
  {
    time: '2020-11-09',
    title: '科克华人商会代表团参加第11届欧洲论坛',
    href: '/a/news/shdt/123.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-1-2.jpg',
    img_src: '../uploads/allimg/200117/1-20011FUU0926.jpg',
    desc: '2019年10月17－19日，由全欧华人专业协会联合会主办，爱尔兰华人专业协会承办，科克华人商会提供赞助的第11届欧洲论坛在都柏林成功举办。\n    本届“欧洲论坛”的主题是“创新、多元、合作”。近300名来自欧洲各地的华人专业人士以及中爱各界人士就人工智能、5G互联、生物医药、英国“脱欧”对中欧合作的影响等话题展开深入讨论。这是来自欧洲所有代表了华人专业领域最高层次的盛会，科克华人商会代表团成员全程参与了本次论坛所有活动及主题讲座，并积极和来自世界各地的华人代表、教授学者，政府和企业部门人员进行了广泛的交流探讨，学习了解了多方面的发展趋势，也对商会的未来发展提供了重要的引导方向。',
    id: 'shdt-1',
  },
  {
    time: '2020-01-10',
    title: '第六届世界闽商大会',
    href: '/a/news/shdt/124.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-2-2.jpg',
    img_src: '../uploads/allimg/200110/1-200110101241646.jpg',
    desc: '2019年6月18日，科克华人商会李积旺理事代表商会参加第六届世界闽商大会、第十七届中国·海峡创新项目成果交易会和第九届福建省民营企业产业项目对接洽谈会。来自100多个国家和地区的闽商与海内外嘉宾等1800多人齐聚榕城，共话创新创业创造，凝心凝智凝力，增强信心力量，坚定不移扩大高水平对外开放和积极参与经济全球化，坚持做好自己的事。',
    id: 'shdt-2',
  },
  {
    time: '2020-01-10',
    title: '爱尔兰科克市市长接见科克市华文学校师生以及',
    href: '/a/news/shdt/122.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-3-1.jpg',
    img_src: '../uploads/allimg/200110/1-200110100J9396.jpg',
    desc: '科克市华文学校，成立于草长莺飞的季节。成立两个月以来，中文语言教学分三个等级共十个班次有条不紊的推进，课外辅导课、中国传统武术班、绘画特长班、钢琴基础班等兴趣课也得到了学生家长的热烈响应，正如窗外五月的爱尔兰，一切都是生气勃勃、生机盎然。',
    id: 'shdt-3',
  },
  {
    time: '2020-01-10',
    title: '爱尔兰科克华人商会成立仪式',
    href: '/a/news/shdt/121.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-4-3.jpg',
    img_src: '../uploads/allimg/200110/1-200110100403639.jpg',
    desc: '爱尔兰科克华人商会成立仪式于科克市市政厅圆满举行\n    2018年9月23日，爱尔兰科克华人商会成立仪式暨首届理事会就职典礼在科克市市政厅大礼堂圆满举行。本次晚会由中国驻爱尔兰大使馆，科克市政府, 科克华人商会，新岛周报，中爱传媒协会联合主办。',
    id: 'shdt-4',
  },
  {
    time: '2020-01-10',
    title: '爱尔兰科克华人商会代表团访问大连',
    href: '/a/news/shdt/120.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-5-5.jpg',
    img_src: '../uploads/allimg/200110/1-20011010001G52.jpg',
    desc: '2019年 4月8日，以林雄为团长的爱尔兰科克华人商会代表团一行访问大连。\n    代表团首先考察了越洋物语（大连）运营管理有限公司线下商品展示中心，并就开展两地海产品养殖、深加工、跨境经贸等方面同企业进行了研讨。',
    id: 'shdt-5',
  },
  {
    time: '2020-01-10',
    title: '李卓彬副主席会见爱尔兰科克华人商会访问团',
    href: '/a/news/shdt/119.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-6-2.jpg',
    img_src: '../uploads/allimg/200110/1-200110095Q6235.jpg',
    desc: '4月3日上午，中国侨联副主席李卓彬在中国侨联机关会见了以林雄为团长的爱尔兰科克华人商会代表团一行。\n    李卓彬首先代表中国侨联对代表团的来访表示热烈欢迎。他详细询问了爱尔兰和科克市有关情况，尤其是当地华侨华人的生存发展情况。他指出，经过几十年的努力，科克华侨华人在传统产业已经有了很好的基础，面对新的形势，要抓住“一带一路”建设的历史性契机，进一步拓展与中国的进出口贸易，加快转型升级发展。他表示，中国侨联是广大侨胞的娘家，为侨服务是侨联组织宗旨，希望大家能够常回家看看，加强沟通和联系；同时也希望科克华侨华人加强团结，与当地政府和人民友好相处，积极融入当地社会，支持我驻爱使领馆工作，为促进中爱两国友谊作出贡献。',
    id: 'shdt-6',
  },
  {
    time: '2020-01-10',
    title: '爱尔兰科克华人商会应邀出席庆祝中国与爱尔兰',
    href: '/a/news/shdt/118.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-7-1.jpg',
    img_src: '../uploads/allimg/200110/1-20011009553B03.jpg',
    desc: '2019年6月20日爱尔兰科克华人商会代表应邀出席了在都柏林会议中心举行的庆祝中爱两国建交40周年活动。商会代表团成员为科克市华人商会会长林雄先生；科克市华人商会理事长陈爱春先生；科克市华人商会常务副会长林波先生；科克市华人商会秘书长单玉武先生。',
    id: 'shdt-7',
  },
  {
    time: '2020-01-10',
    title: '科克市华人商会＂智囊风暴工作室＂研讨会顺利',
    href: '/a/news/shdt/117.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-8-1.jpg',
    img_src: '../uploads/allimg/200110/1-2001100953451A.jpg',
    desc: '2019年5月14日，科克华人商会高级顾问Pat Ledwidge (前科克市政厅副执行长官兼战略规划及经济发展局局长)受商会委托，在科克大学为商会成员举办一场"智囊风暴工作室"主题研讨会，商会政务顾问王少敏担任翻译。',
    id: 'shdt-8',
  },
  {
    time: '2020-01-10',
    title: '浙江省台州市访问团拜访科克市政府及科克华人',
    href: '/a/news/shdt/116.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-9-1.jpg',
    img_src: '../uploads/allimg/200110/1-20011009511N31.jpg',
    desc: '2019年6月17日下午，科克市华人商会理事长陈爱春代表华人商会在科克市市政厅会见浙江省台州市访问团一行，并就经济、贸易、农业等话题进行了深入交流。\n    浙江省台州市访问团成员有：台州市人大常委会副主任赵跃进，台州市人大常委会委员、民宗侨外工委副主任李勃，台州市市委组织部副部长林慷，台州市文广旅体局副局长徐景宝，台州市商务局副局长余昌斌，台州市人民政府经济合作办公室潘优优。',
    id: 'shdt-9',
  },
  {
    time: '2020-01-10',
    title: '科克华文学校揭牌仪式',
    href: '/a/news/shdt/115.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-10-2.jpg',
    img_src: '../uploads/allimg/200110/1-200110094U2U8.jpg',
    desc: '2019年4月18日晚，科克华人商会于兰花庭餐厅顺利举办“Pat Ledwidge 荣休晚宴暨科克华文学校揭牌仪式”。\n    活动当天不仅邀请到了多位科克市政府贵宾，众多各行业的精英人士也出席了活动现场，共同见证Pat先生的荣休并为科克华文学校的成立到场祝贺。',
    id: 'shdt-10',
  },
  {
    time: '2020-01-10',
    title: '冯志农郑惠文会见爱尔兰科克市华人商会访问团',
    href: '/a/news/shdt/114.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-11-1.jpg',
    img_src: '../uploads/allimg/200110/1-200110094FQ35.jpg',
    desc: '省委统战部副部长、省侨办主任冯志农（右四），省委统战部部务会议成员郑惠文（右三）与爱尔兰科克市华人商会访问团一行合影。\n    2019年4月10日，福建省委统战部副部长、省侨办主任冯志农，省委统战部部务会议成员郑惠文在福州会见爱尔兰科克市华人商会访问团。',
    id: 'shdt-11',
  },
  {
    time: '2020-01-10',
    title: '何向东大使访问科克',
    href: '/a/news/shdt/113.html',
    imgPwd: '../ECMS_DGSJ/images/news/shdt-12-1.jpg',
    img_src: '../uploads/allimg/200110/1-2001100941094I.jpg',
    desc: '2019年9月22日至24日，应科克郡、市政府邀请，何向东大使夫妇访问位于爱尔兰岛南部的科克郡和科克市。\n    在会见科克郡郡长奥沙利文、郡首席行政官卢希和科克市市长希恩、市首席行政官多赫蒂时，何大使介绍了中爱互惠战略伙伴关系和两国各领域务实合作近况，赞赏科克郡、市发展对华关系、促进中爱友谊的热情，希望科克郡、市抓住中爱关系快速发展的机遇，与中国有关省、市进一步深化友好往来与合作。奥沙利文郡长、希恩市长等介绍了科克郡、市与江苏省、上海市等交往与合作的情况，表示科克郡、市高度重视并将不断加强同中国省市的友好往来，增进相互了解与友谊，扩大经贸、旅游、人文等领域合作，实现互惠、共赢并为爱中关系发展作出积极贡献。欢迎更多中国企业前来科克投资兴业。',
    id: 'shdt-12',
  },
];

const newsData = [
  // {
  //   time: '2020-12-01',
  //   title: '【圣诞福利来袭】快来围观爱尔兰政府30项社会福',
  //   href: '/a/xinxizixun/2020/1201/212.html',
  //   imgPwd: '',
  //   img_src: '',
  //   desc: '爱尔兰社会保护部长今天确认，\n    今年的圣诞福利金将支付给\n    160多\n    万人，总计\n    3.9\n    亿欧元。\n    所有有权获得圣诞节社会福利接收者都将在\n    12\n    月',
  //   id: 'news-1',
  // },
  // {
  //   time: '2020-12-01',
  //   title: '2019年爱尔兰移民法案解读（2020年移民局尚未更新',
  //   href: '/a/xinxizixun/2020/1201/211.html',
  //   imgPwd: '',
  //   img_src: '',
  //   desc: '《2019年爱尔兰投资移民法案》\n    2020年爱尔兰投资移民申请法案延续2019年移民法案继续执行。\n    爱尔兰政府保持一贯对海外移民的欢迎态度。\n    1. 爱尔兰投资移民\n    没有任何配额',
  //   id: 'news-2',
  // },
  // {
  //   time: '2020-11-23',
  //   title: '欧洲第一世界第二，爱尔兰食品安全排名',
  //   href: '/a/xinxizixun/2020/1121/209.html',
  //   imgPwd: '',
  //   img_src: '',
  //   desc: '据悉，《经济学人》智库发布2019年全球食品安全指数排名，在全球113个国家和地区中，爱尔兰以84.0的综合\n    得分排名第二，这也是爱尔兰连续第二年蝉联全球食品安全TOP榜。\n    “全球食品安全指数”是一个动态的定量和定性基准模型，由34个独特的指标构建而成，可衡量发展中国家和发达国家的食品安全驱动因素。该指数是第一个从国际上确定的三个指标（食品的可负担性、供应充足程度、质量与安全）来全面审查食品安全的指数。',
  //   id: 'news-3',
  // },
  {
    time: '2020-11-22',
    title: '学习借鉴国际友城 新时代走在最前列 | 科克：倾',
    href: '/a/xinxizixun/2020/1121/210.html',
    imgPwd:
      'https://5b0988e595225.cdn.sohucs.com/q_70,c_zoom,w_640/images/20181204/9fd152e06c144e5fa453bead1d38bb97.jpeg',
    img_src:
      'https://5b0988e595225.cdn.sohucs.com/q_70,c_zoom,w_640/images/20181204/9fd152e06c144e5fa453bead1d38bb97.jpeg',
    desc: '庆祝改革开放40周年大型报道\n    《学习借鉴国际友城 新时代走在最前列》\n    采访团队来到了第3站——爱尔兰科克\n    科克：倾力打造科技创新生态\n    “We are Cork（我们是科克人）”，这句口号醒目地矗立在深圳友好交流城市——爱尔兰科克市政厅前的广场上。当科克市市长米克·芬恩讲到这句口号的含义时，本报特派采访小分队的成员不约而同地说，在深圳很早就有一句话，叫“来了，就是深圳人”，这与“我们是科克人”有异曲同工之妙。芬恩听后，开始有些诧异，然后突然理解，大家都心领神会地笑了！',
    id: 'news-4',
  },
  // {
  //   time: '2020-11-21',
  //   title: '“爱”心传递 爱尔兰华侨华人奋战新冠病毒',
  //   href: '/a/xinxizixun/2020/1121/208.html',
  //   imgPwd: '../ECMS_DGSJ/images/news/news-5-1.jpg',
  //   img_src: '../uploads/allimg/201121/1RRA329-0.jpg',
  //   desc: '【欧洲时报记者陈斯睿、田皓雪子报道】新型冠状病毒疫情蔓延还在不断发酵中，据悉，截至2月3日，全球范围内确诊20623例，欧洲境内确诊27例。据《爱尔兰时报》，用于新型冠状病毒的新检测试剂盒已在爱尔兰使用，该试剂盒可在四至六小时内产生结果。虽然截至目前，爱尔兰还未有人确诊感染，然而湖北疫情时刻牵动着在爱华人的心，他们自发组织募捐募集善款及物资，发往湖北疫区。本报记者据此对爱尔兰华人专业人士协会、爱尔兰科克华人商会、爱心社等华人组织负责人进行采访，了解募捐的具体情况及进展。',
  //   id: 'news-5',
  // },
  // {
  //   time: '2020-11-13',
  //   title: '何向东大使出席2020年中爱商务视频峰会',
  //   href: '/a/xinxizixun/2020/1113/205.html',
  //   imgPwd:
  //     'https://mmbiz.qpic.cn/mmbiz_png/SDrdLcd7UcMNuvIN7wAlmnBKmMrrEuMOGptLZQt2SGJ6tWvyDf2Aq3uRjlXSiaFO1nXlPibyWgibyFKrT8Mxozdpw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
  //   img_src:
  //     'https://mmbiz.qpic.cn/mmbiz_png/SDrdLcd7UcMNuvIN7wAlmnBKmMrrEuMOGptLZQt2SGJ6tWvyDf2Aq3uRjlXSiaFO1nXlPibyWgibyFKrT8Mxozdpw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1',
  //   desc: '9月24日至25日，爱尔兰智库“亚洲事务论坛”举办2020年中爱商务视频峰会。何向东大使、爱公共支出与改革部长麦格拉斯及来自两国有关地方政府和经贸、教育、文旅等部门及企业、机构、社团的500多名代表共同出席。何大使发表了讲话。',
  //   id: 'news-6',
  // },
  {
    time: '2020-11-13',
    title: '爱尔兰旅游局致中国旅业同仁的一封信',
    href: '/a/xinxizixun/2020/1113/204.html',
    imgPwd: '../ECMS_DGSJ/images/news/news-7-1.jpg',
    img_src: '',
    desc: '爱尔兰旅游局致中国旅业同仁的一封信\n    当前全球旅游业正处于持续不稳定的阶段，我衷心希望您和您的团队及家人一切安好。今年夏天，爱尔兰岛的旅游业已向国内游客开放。尽管已有不少很棒的本国旅行，爱尔兰的旅游业者仍然期待在恰当的时候欢迎来自海外的游客。',
    id: 'news-7',
  },
  {
    time: '2020-11-13',
    title: '爱尔兰城堡：镶嵌在翡翠岛上的珠宝',
    href: '/a/xinxizixun/2020/1113/203.html',
    imgPwd: '../ECMS_DGSJ/images/news/news-8-1.jpg',
    img_src:
      'https://www.roadaffair.com/wp-content../uploads/2017/12/rock-of-cashel-castle-ireland-shutterstock_750976849.jpg',
    desc: '爱尔兰，一直有“翡翠岛”之美誉。\n    它似一块清澈剔透的绿翡翠，点缀在蔚蓝的大西洋之上。\n    如果把镜头推近，你会发现这块翠碧之上另有珠宝镶嵌。\n    那就是散落在爱尔兰各地的\n    城堡',
    id: 'news-8',
  },
  {
    time: '2020-11-13',
    title: '科夫：糖果色的“心碎小镇”',
    href: '/a/xinxizixun/2020/1113/202.html',
    imgPwd: '../ECMS_DGSJ/images/news/news-9-1.jpg',
    img_src:
      'https://lh3.googleusercontent.com/proxy/8MOHWENcrp7FLi-4eaa_PjNdlAZ1J8wEp3u4ECP-ymxFB6jCp--bpu3pGjBK12QH3FWuj6HPkJJKA3_EOpuzOloHSgtLKXzWRCPcdcVLsOrbIKIxnYJb',
    desc: '俯瞰爱尔兰，勾勒翡翠岛轮廓的每个点都是一处天涯海角。\n    那些散落在岛屿边缘的城镇，因受海风海浪的漫长雕琢而更显硬朗，也因各具历史与民俗而散发着不同的光芒。\n    这其中璀璨夺目的，科夫小镇（Cobh）算得上一个。',
    id: 'news-9',
  },
  // {
  //   time: '2020-11-13',
  //   title: '爱尔兰的秋天是什么味道？',
  //   href: '/a/xinxizixun/2020/1113/201.html',
  //   imgPwd:
  //     'https://mmbiz.qpic.cn/mmbiz_gif/QJXF7t0V2TP05GTMfhWfD6zSicekFibUHfeL7c4hdzCBSFicOUUH2ZfsQCTTKWhYbXOVSBxLVibQmjAvRNibvonGsSA/640?wx_fmt=gif',
  //   img_src:
  //     'https://mmbiz.qpic.cn/mmbiz_gif/QJXF7t0V2TP05GTMfhWfD6zSicekFibUHfeL7c4hdzCBSFicOUUH2ZfsQCTTKWhYbXOVSBxLVibQmjAvRNibvonGsSA/640?wx_fmt=gif',
  //   desc: '爱尔兰的秋天是什么味道？\n    原创\n    三叶草君\n    爱尔兰旅游局\n    10月20日\n    秋天的关键词只有枫叶、丰收吗？\n    NO！\n    爱尔兰的秋天除了山脉上渐变的色彩\n    还“有滋有味”',
  //   id: 'news-10',
  // },
  {
    time: '2020-01-10',
    title: '科克市介绍',
    href: '/a/xinxizixun/2020/0110/110.html',
    imgPwd: '../ECMS_DGSJ/images/news/news-11-1.jpg',
    img_src: '../uploads/allimg/200110/1-2001100916132G.jpg',
    desc: '科克，爱尔兰语中意为“湿地”“沼泽”，是爱尔兰第二大城市，位于爱尔兰西南部，也是芒斯特省最大的城市，根据爱尔兰2016年的人口调查，其人口达到125,657人，但在最新2019年的边界变动之后其人口也随之增长为210,000人。',
    id: 'news-11',
  },
];

const allDataForNews = [...shdtData, ...announcementData, ...newsData];

const newsSubNavMap = new Map([
  ['shdt', 0],
  ['announcement', 1],
  ['news', 2],
]);
